language: python

python:
  - 2.6
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1

matrix:
  exclude:
    - env: DJANGO_VERSION=1.4.5
      python: 3.3


install:
  - pip install django==$DJANGO_VERSION
  - pip install factory-boy
  - python setup.py develop

script: cd example_project; python manage.py test photologue

