language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO="Django==1.6.7"
  - DJANGO="Django==1.7"

matrix:
  exclude:
    # Python 3.4 is not supported in Django before 1.7.
    - env: DJANGO="Django==1.6.7"
      python: 3.4
    # Python 2.6 support has been dropped in Django 1.7
    - python: 2.6
      env: DJANGO="Django==1.7"

install:
  - pip install $DJANGO
  - pip install factory-boy
  - pip install pytz
  - pip install south==0.8.4 # Only required for Django 1.6, but does no harm if installed for 1.7.
  - python setup.py develop

script: cd example_project; python manage.py test photologue

