dist: xenial
sudo: false
language: python

# Travis config is driven by the tox.ini file.

# Here we just specify:
# 1. The Python versions to run - it will start a CI server for each, and run all the tox environments
#    that use that Python. So in Travis we are running both in parallel (one server per Python version)
#    and in series (each server runs all the Django envs for that version of Python).

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r example_project/requirements.txt
  - pip install tox-travis
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then pip install coveralls; fi

script:
  # Run against all the Python interpreter and Django versions specified in the tox.ini file.
  - tox
  # Coveralls only needs to run once - so run it against just one Python interpreter.
  # TODO Specifying the exact Django version here as 2.2 has been released, but Photologue is not compatible yet.
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then pip install django==2.1.8 && cd example_project && coverage run manage.py test photologue; fi

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then coveralls; fi
